import hashlib
import json
import socket
import platform
from datetime import datetime, timezone
from typing import Dict, Any, Optional

class EvidenceService:
    """
    Cryptographic Chain-of-Custody and Digital Evidence Certification Service.
    Produces court-admissible certificates compliant with:
    - Section 65B of the Indian Evidence Act, 1872
    - Section 63 of the Bharatiya Sakshya Adhiniyam, 2023 (BSA)
    """

    @staticmethod
    def compute_canonical_hash(trace_data: Dict[str, Any]) -> str:
        """
        Computes SHA-256 fingerprint from canonical JSON representation.
        Excludes volatile fields like previous hash or temporary report tokens.
        """
        canonical_obj = {
            "nodes": trace_data.get("nodes", []),
            "edges": trace_data.get("edges", []),
            "intelligence": trace_data.get("intelligence", {}),
            "trace_metadata": trace_data.get("trace_metadata", {})
        }
        serialized = json.dumps(canonical_obj, sort_keys=True, separators=(',', ':'))
        return hashlib.sha256(serialized.encode('utf-8')).hexdigest()

    @staticmethod
    def generate_certificate(investigation_id: str, sha256_hash: str, officer_name: str = "Insp. Aditya Prashant Deshmukh", officer_badge: str = "CY-MH-4019") -> Dict[str, Any]:
        cert_id = f"CERT-65B-{investigation_id.upper()}"
        now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        attestation_clause = (
            "I, the undersigned investigating cyber forensic examiner, hereby certify under "
            "Section 65B of the Indian Evidence Act, 1872 and Section 63 of the Bharatiya Sakshya Adhiniyam, 2023 (BSA) "
            "that the cryptographic ledger trail, transaction graph, and attribution findings contained herein "
            "were generated by TRACE-X automated blockchain forensics software in the ordinary course of lawful official duties. "
            "The computer system and blockchain indexing interfaces operated in an uncompromised condition with cryptographic "
            "integrity validated via SHA-256 hash digest verification."
        )

        return {
            "certificate_id": cert_id,
            "statutory_act": "Section 65B Indian Evidence Act 1872 / Section 63 Bharatiya Sakshya Adhiniyam 2023",
            "sha256_digest": sha256_hash,
            "verification_status": "CRYPTOGRAPHICALLY_VERIFIED",
            "timestamp": now_utc,
            "certifying_officer": officer_name,
            "officer_badge": officer_badge,
            "station": "Cyber Crime Police Station / MIT AOE Cyber Forensics Lab",
            "terminal_id": socket.gethostname(),
            "os_environment": f"{platform.system()} {platform.release()}",
            "attestation_text": attestation_clause
        }

    @staticmethod
    def verify_hash(sha256_or_id: str) -> Dict[str, Any]:
        """
        Verify if a given SHA-256 hash or Investigation ID corresponds to an authentic,
        unaltered investigation stored in the persistent database.
        """
        try:
            from app.db.database import get_connection
            conn = get_connection()
            cur = conn.cursor()
            
            cur.execute("""
                SELECT id, start_address, chain, risk_score, risk_level, hash_sha256, created_at 
                FROM investigations 
                WHERE hash_sha256 = ? OR id = ?
            """, (sha256_or_id, sha256_or_id))
            row = cur.fetchone()
            conn.close()

            if row:
                return {
                    "is_valid": True,
                    "status": "AUTHENTIC_RECORD_FOUND",
                    "investigation_id": row["id"],
                    "start_address": row["start_address"],
                    "chain": row["chain"],
                    "risk_score": row["risk_score"],
                    "risk_level": row["risk_level"],
                    "canonical_sha256": row["hash_sha256"],
                    "recorded_at": row["created_at"],
                    "evidence_admissibility": "COURT_ADMISSIBLE (Section 65B/63 BSA Validated)",
                    "message": "Cryptographic integrity check passed. Record matches immutable database state."
                }
            else:
                return {
                    "is_valid": False,
                    "status": "RECORD_NOT_FOUND",
                    "message": "No matching investigation record found with the supplied cryptographic digest."
                }
        except Exception as e:
            return {
                "is_valid": False,
                "status": "VERIFICATION_ERROR",
                "message": str(e)
            }
